# Generated by Django 3.2 on 2023-07-27 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('view_count', models.BigIntegerField(default=0, verbose_name='Счётчик просмотров')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.content')),
                ('bitrate', models.IntegerField(verbose_name='Битрейт, Бит/с')),
            ],
            bases=('api.content',),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.content')),
                ('content', models.TextField(max_length=5000, verbose_name='Текст')),
            ],
            bases=('api.content',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.content')),
                ('file_link', models.URLField(verbose_name='Ссылка на файл видео')),
                ('subtitles_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на файл субтитров')),
            ],
            bases=('api.content',),
        ),
        migrations.AddField(
            model_name='content',
            name='pages',
            field=models.ManyToManyField(blank=True, default=[], to='api.Page', verbose_name='Страницы'),
        ),
    ]
